//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCF_Functions.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UNITS_BORE_MM {
            get {
                return ((bool)(this["UNITS_BORE_MM"]));
            }
            set {
                this["UNITS_BORE_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNITS_BORE_INCH {
            get {
                return ((bool)(this["UNITS_BORE_INCH"]));
            }
            set {
                this["UNITS_BORE_INCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UNITS_CO_ORDS_MM {
            get {
                return ((bool)(this["UNITS_CO_ORDS_MM"]));
            }
            set {
                this["UNITS_CO_ORDS_MM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNITS_CO_ORDS_INCH {
            get {
                return ((bool)(this["UNITS_CO_ORDS_INCH"]));
            }
            set {
                this["UNITS_CO_ORDS_INCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UNITS_WEIGHT_KGS {
            get {
                return ((bool)(this["UNITS_WEIGHT_KGS"]));
            }
            set {
                this["UNITS_WEIGHT_KGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNITS_WEIGHT_LBS {
            get {
                return ((bool)(this["UNITS_WEIGHT_LBS"]));
            }
            set {
                this["UNITS_WEIGHT_LBS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UNITS_WEIGHT_LENGTH_METER {
            get {
                return ((bool)(this["UNITS_WEIGHT_LENGTH_METER"]));
            }
            set {
                this["UNITS_WEIGHT_LENGTH_METER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNITS_WEIGHT_LENGTH_INCH {
            get {
                return ((bool)(this["UNITS_WEIGHT_LENGTH_INCH"]));
            }
            set {
                this["UNITS_WEIGHT_LENGTH_INCH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UNITS_WEIGHT_LENGTH_FEET {
            get {
                return ((bool)(this["UNITS_WEIGHT_LENGTH_FEET"]));
            }
            set {
                this["UNITS_WEIGHT_LENGTH_FEET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ALL_PIPELINES {
            get {
                return ((bool)(this["ALL_PIPELINES"]));
            }
            set {
                this["ALL_PIPELINES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SPECIFIC_PIPELINE {
            get {
                return ((bool)(this["SPECIFIC_PIPELINE"]));
            }
            set {
                this["SPECIFIC_PIPELINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SYS_ABBR_SPEC_PIPL {
            get {
                return ((string)(this["SYS_ABBR_SPEC_PIPL"]));
            }
            set {
                this["SYS_ABBR_SPEC_PIPL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("comboBox1")]
        public string DELETE {
            get {
                return ((string)(this["DELETE"]));
            }
            set {
                this["DELETE"] = value;
            }
        }
    }
}
